spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/bookLibrary
    username: postgresUsername
    password: postgresPassword
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /records
  port: 8082